### ISSUE TITLE
README tracker

### ISSUE THREAD

**Issue by snayfach** [snayfach/UHGV#47]
- [ ] Update pipeline image
- [x] Add new databases
- [ ] Detail files in read_mapping directory
- [ ] Provide read mapping protocol
- [ ] Update numbers of viruses
